apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: microservices-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: "<YOUR_GIT_REVISION>"
  timeout: 60s
  url: "<YOUR_GIT_REPOSITORY_URL>"
